name: Meu Primeiro Workflow

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  rodar-verificacao:
    name: Rodar verificação automática
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Instalar o .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restaurar dependências
        run: dotnet restore github4women/github4women.csproj

      - name: Build do projeto
        run: dotnet build github4women/github4women.csproj --configuration Release

      - name: Rodar testes (se tiver)
        run: dotnet test github4women/github4women.csproj
        continue-on-error: true
        
